name: Build & deploy documentation on rs.delta.chat, c.delta.chat, py.delta.chat and cffi.delta.chat

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build-rs:
    runs-on: ubuntu-latest
    environment:
      name: rs.delta.chat
      url: https://rs.delta.chat/

    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
          persist-credentials: false

      - name: Build the documentation with cargo
        run: |
          cargo doc --package deltachat --no-deps --document-private-items

      - name: Upload Rust docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltachat-rs-docs
          path: ${{ github.workspace }}/target/doc/
          retention-days: 30

  build-python:
    runs-on: ubuntu-latest
    environment:
      name: py.delta.chat
      url: https://py.delta.chat/

    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
          persist-credentials: false
          fetch-depth: 0 # Fetch history to calculate VCS version number.

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Build Python documentation
        run: nix build .#python-docs

      - name: Upload Python docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltachat-python-docs
          path: ${{ github.workspace }}/result/html/
          retention-days: 30

  build-c:
    runs-on: ubuntu-latest
    environment:
      name: c.delta.chat
      url: https://c.delta.chat/

    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
          persist-credentials: false
          fetch-depth: 0 # Fetch history to calculate VCS version number.

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Build C documentation
        run: nix build .#docs

      - name: Upload C docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltachat-c-docs
          path: ${{ github.workspace }}/result/html/
          retention-days: 30

  build-ts:
    runs-on: ubuntu-latest
    environment:
      name: js.jsonrpc.delta.chat
      url: https://js.jsonrpc.delta.chat/

    defaults:
      run:
        working-directory: ./deltachat-jsonrpc-bindings/typescript

    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
          persist-credentials: false
          fetch-depth: 0 # Fetch history to calculate VCS version number.

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: Run docs script
        run: npm run docs

      - name: Upload TS docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltachat-ts-docs
          path: ${{ github.workspace }}/deltachat-jsonrpc-bindings/typescript/docs/
          retention-days: 30

  build-cffi:
    runs-on: ubuntu-latest
    environment:
      name: cffi.delta.chat
      url: https://cffi.delta.chat/

    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
          persist-credentials: false

      - name: Build the documentation with cargo
        run: |
          cargo doc --package deltachat_ffi --no-deps

      - name: Upload CFFI docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltachat-cffi-docs
          path: ${{ github.workspace }}/target/doc/
          retention-days: 30
